version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: adminpass
      POSTGRES_USER: pcrsadmin
      POSTGRES_DB: hintservice
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    env_file:
      - .env
    environment:
      - DB_HOST=db

volumes:
  db_data: